# Generated by Django 5.0.3 on 2024-03-11 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='start_datetime',
            new_name='startDateTime',
        ),
        migrations.AddField(
            model_name='task',
            name='stopDateTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
