# Generated by Django 5.0.3 on 2024-03-12 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_rename_start_datetime_task_startdatetime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='stop_datetime',
        ),
    ]
